#!/usr/bin/env node
//
// styles.senate.css and styles.house.css must be styles.css as dev/split-css.mjs would generate
// them today.
//
// WHY THIS EXISTS
// Both pages load a stylesheet GENERATED from styles.css: the House's is the same file with its
// comments removed and nothing else changed; the Senate's also leaves out every rule that names a
// class or id the Senate page never uses, in the original order. styles.css stays the one source
// of truth, but that means a change to it (or, for the Senate, to senate.html or a script it
// loads) reaches a page only once its file is regenerated, and nothing else would notice if it
// were not: the page would just keep the old CSS. This fails until `npm run css` has been run.
// No network, no dependencies.

import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { senateCss, houseCss, stripComments, universe, parse, SENATE_FILES } from '../dev/split-css.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const committed = readFileSync(join(ROOT, 'styles.senate.css'), 'utf8');
const house = readFileSync(join(ROOT, 'styles.house.css'), 'utf8');
const source = readFileSync(join(ROOT, 'styles.css'), 'utf8');
let n = 0;
const ok = (name, fn) => { fn(); n++; console.log('ok  ' + name); };

ok('styles.senate.css is current (run `npm run css` if this fails)', () => {
  assert.strictEqual(committed, senateCss(), 'styles.css or a Senate script changed: run `npm run css`');
});

ok('styles.house.css is current (run `npm run css` if this fails)', () => {
  assert.strictEqual(house, houseCss(), 'styles.css changed: run `npm run css`');
});

ok('the Senate file is smaller than the source, and says it is generated', () => {
  assert.ok(committed.length < source.length * 0.7);
  assert.ok(/^\/\* GENERATED by dev\/split-css\.mjs/.test(committed));
});

ok('a rule for a class only the House page uses is gone, and a Senate one is kept', () => {
  assert.ok(!/\.oath-section\b/.test(committed), '.oath-section is the House oath panel');
  assert.ok(/\.qb-member\b/.test(committed), '.qb-member is the Senate grid');
  assert.ok(/\.sen-desk\b/.test(committed) || /\.qb-desk\b/.test(committed), 'the chamber map desks');
});

ok('no rule that applies to the static senate.html markup is dropped', () => {
  // Rule by rule, not class by class: a class can have a rule only under a House-only parent
  // (.party-breakdown-indicator .indicator-dot), and dropping that one is right. The invariant is
  // that a selector whose every class and id is in senate.html's own markup is KEPT, so the
  // generator can never lose a rule the page's static elements could match.
  const html = readFileSync(join(ROOT, 'senate.html'), 'utf8');
  const names = new Set();
  for (const m of html.matchAll(/class="([^"]+)"/g)) for (const c of m[1].split(/\s+/)) if (c) names.add(c);
  for (const m of html.matchAll(/\sid="([^"]+)"/g)) names.add(m[1]);
  const flat = (t) => t.replace(/\s+/g, ' ');
  const out = flat(committed);
  const walk = (nodes) => nodes.flatMap((nd) => nd.children ? walk(nd.children) : nd.kind === 'rule' ? [nd] : []);
  const lost = [];
  for (const r of walk(parse(source.replace(/\/\*[\s\S]*?\*\//g, '')))) {
    for (const sel of r.prelude.split(/,(?![^(\[]*[)\]])/).map((x) => x.trim())) {
      if (sel.includes('[data-chamber="house"]')) continue;
      const bare = sel.replace(/\([^)]*\)|\[[^\]]*\]/g, '');
      const needs = [...bare.matchAll(/[.#](-?[_a-zA-Z][\w-]*)/g)].map((m) => m[1]);
      if (needs.length && needs.every((c) => names.has(c)) && !out.includes(flat(sel))) lost.push(sel);
    }
  }
  assert.deepStrictEqual(lost, [], `selectors that apply to senate.html but are not in the Senate file: ${lost.slice(0, 5).join(' | ')}`);
});

ok('the cascade is the original: the @layer and the unlayered override survive in order', () => {
  assert.ok(committed.includes('@layer app {'));
  assert.ok(committed.indexOf('@layer app {') < committed.lastIndexOf('}'));
});

ok('every @keyframes kept is used by a kept rule or a Senate script', () => {
  const uni = universe(SENATE_FILES);
  for (const m of committed.matchAll(/@keyframes\s+([\w-]+)/g)) {
    const used = new RegExp(`(?:animation(?:-name)?\\s*:[^;{}]*|[\\s,])${m[1].replace(/[-]/g, '\\-')}(?![\\w-])`).test(committed.replace(/@keyframes\s+[\w-]+/g, '')) || uni.words.has(m[1]);
    assert.ok(used, `@keyframes ${m[1]} is kept but nothing names it`);
  }
});

// ---- the House file: styles.css with its comments removed and NOTHING else ---------------------

// Both sides reduced to a token stream: whitespace around punctuation is not meaningful in CSS
// outside strings, and styles.css has no string or url() containing "/*" (asserted below), so a
// plain regex is a fair independent way to take the comments out of the source.
const tokens = (css) => css.replace(/\s+/g, ' ').replace(/\s*([{};:,>+~])\s*/g, '$1').trim();

ok('no string or url() in styles.css contains a comment opener', () => {
  const bad = [...source.matchAll(/("[^"\n]*\/\*[^"\n]*"|'[^'\n]*\/\*[^'\n]*'|url\([^)]*\/\*[^)]*\))/g)].map((m) => m[0]);
  assert.deepStrictEqual(bad, []);
});

ok('the House file is the source minus its comments, token for token', () => {
  const body = house.replace(/^\/\*[\s\S]*?\*\//, '');          // its own header
  assert.strictEqual(tokens(body), tokens(source.replace(/\/\*[\s\S]*?\*\//g, ' ')));
});

ok('nothing is dropped or reordered: the same rules in the same order', () => {
  const rules = (css) => [...css.replace(/\/\*[\s\S]*?\*\//g, ' ').matchAll(/([^{}]+)\{/g)].map((m) => tokens(m[1]));
  assert.deepStrictEqual(rules(house.replace(/^\/\*[\s\S]*?\*\//, '')), rules(source));
});

ok('it is meaningfully smaller than the source, and says it is generated', () => {
  assert.ok(house.length < source.length * 0.9);
  assert.ok(/^\/\* GENERATED by dev\/split-css\.mjs/.test(house));
});

ok('stripComments: strings and url() are not comments', () => {
  assert.strictEqual(stripComments('a{content:"/* not */";b:url(x/*y.png)}'), 'a{content:"/* not */";b:url(x/*y.png)}');
  assert.strictEqual(stripComments("a{content:'/* not */'}"), "a{content:'/* not */'}");
});

ok('stripComments: a comment between tokens leaves them apart', () => {
  assert.strictEqual(stripComments('a{margin:1px/**/2px}'), 'a{margin:1px 2px}');
  assert.strictEqual(stripComments('a{color:red;/* x */b:c}'), 'a{color:red;b:c}');
  assert.strictEqual(stripComments('/* top */\na{}\n\n\n/* mid */\n\nb{}'), '\na{}\n\nb{}');
});

ok('stripComments: an unterminated comment is an error, not silent truncation', () => {
  assert.throws(() => stripComments('a{} /* oops'), /unterminated/);
});

console.log(`\n${n} passed`);
