#!/usr/bin/env node
//
// Have the sources our explanations cite changed under them?
//
//   node dev/check-sources.mjs
//
// Every (?) popup and panel summary is "Summary generated by AI from CRS Report X (year)": written from one
// edition of a report that CRS can later revise, and a revision can change what we say. This asks the
// Congress.gov API for each cited report's current version and FAILS if it is newer than the one we cite, so the
// failing run (GitHub emails whoever last edited the schedule) is the prompt to re-read it. It also checks that
// the other sources we link (precedents on govinfo, the artwork's page) still answer with the real document and
// not with an error page that says 200.
//
// The citations are read out of the code (dev/sources.js); there is no list to keep.
//
// KEY: CONGRESS_API_KEY if set (free, from api.congress.gov/sign-up, no card). Without one it uses DEMO_KEY, which
// allows only a few calls an hour per IP and a shared CI runner can be throttled, so a 429 is a WARNING, never a
// failure: the check says it could not look, and tries again next week.
//
// Exit 1 on a FAIL. Reads only.

import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { extract, judge } = require('./sources.js');

const KEY = process.env.CONGRESS_API_KEY || 'DEMO_KEY';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const { crs, other } = extract();
const byId = new Map();
for (const c of crs) if (!byId.has(c.id)) byId.set(c.id, c);
// The same report cited at two versions in two places is already a bug.
for (const c of crs) {
  const first = byId.get(c.id);
  if (c.version !== first.version) { console.log(`FAIL  CRS ${c.id}  cited as version ${first.version} in ${first.file} and ${c.version} in ${c.file}`); process.exitCode = 1; }
}

let fails = process.exitCode === 1 ? 1 : 0, warns = 0, oks = 0;
const say = (level, name, msg) => {
  console.log(`${level.padEnd(5)} ${name.padEnd(34)} ${msg}`);
  if (level === 'FAIL') fails++; else if (level === 'warn') warns++; else oks++;
};

async function api(id) {
  const url = `https://api.congress.gov/v3/crsreport/${encodeURIComponent(id)}?api_key=${KEY}&format=json`;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const r = await fetch(url, { headers: { 'User-Agent': UA }, signal: AbortSignal.timeout(30_000) });
      if (r.status === 429) return { throttled: true };
      if (r.status >= 500) { await sleep(2000); continue; }
      if (r.status !== 200) return { error: `HTTP ${r.status}` };
      return { data: (await r.json()).CRSReport };
    } catch (e) { if (attempt) return { error: e.message }; await sleep(2000); }
  }
  return { error: 'no answer' };
}

for (const [id, cite] of byId) {
  const r = await api(id);
  if (r.throttled) say('warn', `CRS ${id}`, 'rate limited, so not checked (set CONGRESS_API_KEY for a reliable check)');
  else if (r.error) say('warn', `CRS ${id}`, `could not look: ${r.error}`);
  else {
    const j = judge(cite, r.data);
    if (j.fail) say('FAIL', `CRS ${id}`, j.fail); else say('ok', `CRS ${id}`, j.ok);
  }
  await sleep(KEY === 'DEMO_KEY' ? 1500 : 250);
}

// Documents we link that are not CRS: must come back as the document, not as a 200 error page.
for (const url of other) {
  const name = url.replace(/^https:\/\/(www\.)?/, '').slice(0, 34);
  try {
    const r = await fetch(url, { headers: { 'User-Agent': UA }, signal: AbortSignal.timeout(30_000), redirect: 'follow' });
    const type = r.headers.get('content-type') || '';
    const wantPdf = /\.pdf$/i.test(url);
    // 403 / 429 / 503 is a site refusing a script (Yale's collection pages do), not a dead link: say so, do not fail.
    if ([403, 429, 503].includes(r.status)) say('warn', name, `HTTP ${r.status}: the site refuses scripts, so not checked`);
    else if (r.status !== 200) say('FAIL', name, `HTTP ${r.status}`);
    else if (wantPdf && !/pdf/i.test(type)) say('FAIL', name, `answers ${type || 'no content type'}, not a PDF (an error page that says 200?)`);
    else if (!wantPdf) {
      const title = ((await r.text()).match(/<title>([^<]*)/i) || [])[1] || '';
      if (/404|not found|error/i.test(title)) say('FAIL', name, `page title says "${title.trim().slice(0, 60)}"`);
      else say('ok', name, 'answers');
    } else say('ok', name, 'a PDF');
  } catch (e) { say('warn', name, `could not look: ${e.message}`); }
}

console.log(`\n${byId.size + other.length} checked: ${oks} ok, ${warns} warn, ${fails} FAIL`);
if (fails) process.exitCode = 1;
