// (?) explanations that are true of both chambers, registered by both boards (see lib/info-popup.js).
// Chamber-specific ones stay in each board's own script.
//
// Each entry is written from a source and shows it, like the House's "Suspension of the Rules":
//
//   key: { title, tags: ['SHORT FACTS'], body: `paragraph\n\nparagraph`, source: 'Summary generated by AI from <a ...>CRS Report ...</a>' }
//
// Pending, one at a time (AGENTS.md, "Explanations: queue and status"): `sap`, the White House memo (a Statement of
// Administration Policy; CRS R44539). Until an entry exists its (?) is not drawn.

(function (root) {
  'use strict';
  root.SharedInfoContent = {};
})(typeof globalThis !== 'undefined' ? globalThis : this);
