// (?) explanations that are true of both chambers, registered by both boards (see lib/info-popup.js).
// Chamber-specific ones stay in each board's own script.
//
// Each entry is written from a source and shows it, like the House's "Suspension of the Rules":
//
//   key: { title, tags: ['SHORT FACTS'], body: `paragraph\n\nparagraph`, source: 'Summary generated by AI from <a ...>CRS Report ...</a>' }
//
// An entry's (?) is drawn only once its entry exists. Queue: AGENTS.md, "Explanations: queue and status".
//
// `sap`: the "White House memo" link on a bill. Every claim is from CRS R44539 (Meghan M. Stuessy, 21 June 2016), the
// only edition; it describes the practice through the Obama Administration, so it says what SAPs do, not what any one
// Administration does. Checked against the report's own text (opened 6 October 2026), claim by claim:
//   issued by OMB on behalf of the Executive Office of the President; speaks for the coordinated Administration; position on legislation scheduled on
//   the floor ("Summary" and "What Are SAPs?"); first public document on a bill; varying support or opposition and
//   particular provisions ("What Are SAPs?", "Example SAP Position Language"); released concurrent with Rules Committee
//   action or floor action; one per bill is frequent but some Administrations issue several as text changes ("SAP Timing");
//   two forms of veto threat, and that "will veto" may leave the President less negotiating room ("Veto Threats").

(function (root) {
  'use strict';
  root.SharedInfoContent = {
    sap: {
      title: 'Statement of Administration Policy',
      tags: ['FROM THE WHITE HOUSE (OMB)', 'SUPPORT OR OPPOSE', 'CAN THREATEN A VETO'],
      body: `A Statement of Administration Policy, or SAP, is the Administration's written position on legislation scheduled for the House or Senate floor. The Office of Management and Budget issues it on behalf of the Executive Office of the President, and it speaks for the Administration as a whole.

An SAP says whether the Administration supports or opposes passage, and how strongly. It may also single out provisions it likes or objects to. It is often the first public document setting out the Administration's views on a bill. SAPs are generally released at the time of Rules Committee action, or of floor action in the House or Senate, and some Administrations issue more than one for a bill as its text changes.

When an SAP threatens a veto it takes one of two forms: that the President will veto the bill, or that the President's senior advisors would recommend a veto. The first can leave the President less room to negotiate afterward.`,
      source: 'Summary generated by AI from <a href="https://www.congress.gov/crs_external_products/R/PDF/R44539/R44539.5.pdf" target="_blank" rel="noopener">CRS Report R44539</a> (2016)'
    }
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
